((nil . ((eval . (setq my-project-dir (concat (locate-dominating-file default-directory ".dir-locals.el"))
                       my-project-include-dir (expand-file-name (concat my-project-dir "src"))
                       flycheck-gcc-include-path (list my-project-include-dir)
                       flycheck-gcc-language-standard "c++11"))
         (eval . (global-set-key [f5] '(lambda ()
                                         (interactive)
                                         (let* ((default-directory my-project-dir))
                                           (call-interactively #'compile)))))
         )))
