/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_biobank_dmscanlib_ScanLib */

#ifndef _Included_org_biobank_dmscanlib_ScanLib
#define _Included_org_biobank_dmscanlib_ScanLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_biobank_dmscanlib_ScanLib
 * Method:    selectSourceAsDefault
 * Signature: ()Lorg/biobank/dmscanlib/ScanLibResult;
 */
JNIEXPORT jobject JNICALL Java_org_biobank_dmscanlib_ScanLib_selectSourceAsDefault
  (JNIEnv *, jobject);

/*
 * Class:     org_biobank_dmscanlib_ScanLib
 * Method:    getDeviceNames
 * Signature: ()Lorg/biobank/dmscanlib/DeviceNamesResult;
 */
JNIEXPORT jobject JNICALL Java_org_biobank_dmscanlib_ScanLib_getDeviceNames
  (JNIEnv *, jobject);

/*
 * Class:     org_biobank_dmscanlib_ScanLib
 * Method:    getValidDpis
 * Signature: (Ljava/lang/String;)Lorg/biobank/dmscanlib/ValidDpisResult;
 */
JNIEXPORT jobject JNICALL Java_org_biobank_dmscanlib_ScanLib_getValidDpis
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_biobank_dmscanlib_ScanLib
 * Method:    getScannerCapability
 * Signature: ()Lorg/biobank/dmscanlib/ValueResult;
 */
JNIEXPORT jobject JNICALL Java_org_biobank_dmscanlib_ScanLib_getScannerCapability
  (JNIEnv *, jobject);

/*
 * Class:     org_biobank_dmscanlib_ScanLib
 * Method:    scanImage
 * Signature: (JLjava/lang/String;JIIDDDDLjava/lang/String;)Lorg/biobank/dmscanlib/ScanLibResult;
 */
JNIEXPORT jobject JNICALL Java_org_biobank_dmscanlib_ScanLib_scanImage
  (JNIEnv *, jobject, jlong, jstring, jlong, jint, jint, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     org_biobank_dmscanlib_ScanLib
 * Method:    scanFlatbed
 * Signature: (JLjava/lang/String;JIILjava/lang/String;)Lorg/biobank/dmscanlib/ScanLibResult;
 */
JNIEXPORT jobject JNICALL Java_org_biobank_dmscanlib_ScanLib_scanFlatbed
  (JNIEnv *, jobject, jlong, jstring, jlong, jint, jint, jstring);

/*
 * Class:     org_biobank_dmscanlib_ScanLib
 * Method:    scanAndDecode
 * Signature: (JLjava/lang/String;JIIDDDDLorg/biobank/dmscanlib/DecodeOptions;[Lorg/biobank/dmscanlib/CellRectangle;)Lorg/biobank/dmscanlib/DecodeResult;
 */
JNIEXPORT jobject JNICALL Java_org_biobank_dmscanlib_ScanLib_scanAndDecode
  (JNIEnv *, jobject, jlong, jstring, jlong, jint, jint, jdouble, jdouble, jdouble, jdouble, jobject, jobjectArray);

/*
 * Class:     org_biobank_dmscanlib_ScanLib
 * Method:    decodeImage
 * Signature: (JLjava/lang/String;Lorg/biobank/dmscanlib/DecodeOptions;[Lorg/biobank/dmscanlib/CellRectangle;)Lorg/biobank/dmscanlib/DecodeResult;
 */
JNIEXPORT jobject JNICALL Java_org_biobank_dmscanlib_ScanLib_decodeImage
  (JNIEnv *, jobject, jlong, jstring, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
