/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_biobank_platedecoder_dmscanlib_ScanLib */

#ifndef _Included_org_biobank_platedecoder_dmscanlib_ScanLib
#define _Included_org_biobank_platedecoder_dmscanlib_ScanLib
#ifdef __cplusplus
extern "C" {
#endif
#undef org_biobank_platedecoder_dmscanlib_ScanLib_MIN_PLATE_NUM
#define org_biobank_platedecoder_dmscanlib_ScanLib_MIN_PLATE_NUM 1L
#undef org_biobank_platedecoder_dmscanlib_ScanLib_MAX_PLATE_NUM
#define org_biobank_platedecoder_dmscanlib_ScanLib_MAX_PLATE_NUM 5L
#undef org_biobank_platedecoder_dmscanlib_ScanLib_SC_SUCCESS
#define org_biobank_platedecoder_dmscanlib_ScanLib_SC_SUCCESS 0L
#undef org_biobank_platedecoder_dmscanlib_ScanLib_SC_FAIL
#define org_biobank_platedecoder_dmscanlib_ScanLib_SC_FAIL -1L
#undef org_biobank_platedecoder_dmscanlib_ScanLib_SC_TWAIN_UNAVAIL
#define org_biobank_platedecoder_dmscanlib_ScanLib_SC_TWAIN_UNAVAIL -2L
#undef org_biobank_platedecoder_dmscanlib_ScanLib_SC_INVALID_DPI
#define org_biobank_platedecoder_dmscanlib_ScanLib_SC_INVALID_DPI -3L
#undef org_biobank_platedecoder_dmscanlib_ScanLib_SC_INVALID_NOTHING_DECODED
#define org_biobank_platedecoder_dmscanlib_ScanLib_SC_INVALID_NOTHING_DECODED -4L
#undef org_biobank_platedecoder_dmscanlib_ScanLib_SC_INVALID_IMAGE
#define org_biobank_platedecoder_dmscanlib_ScanLib_SC_INVALID_IMAGE -5L
#undef org_biobank_platedecoder_dmscanlib_ScanLib_SC_INVALID_NOTHING_TO_DECODE
#define org_biobank_platedecoder_dmscanlib_ScanLib_SC_INVALID_NOTHING_TO_DECODE -6L
#undef org_biobank_platedecoder_dmscanlib_ScanLib_SC_INCORRECT_DPI_SCANNED
#define org_biobank_platedecoder_dmscanlib_ScanLib_SC_INCORRECT_DPI_SCANNED -7L
#undef org_biobank_platedecoder_dmscanlib_ScanLib_CAP_IS_WIA
#define org_biobank_platedecoder_dmscanlib_ScanLib_CAP_IS_WIA 1L
#undef org_biobank_platedecoder_dmscanlib_ScanLib_CAP_DPI_300
#define org_biobank_platedecoder_dmscanlib_ScanLib_CAP_DPI_300 2L
#undef org_biobank_platedecoder_dmscanlib_ScanLib_CAP_DPI_400
#define org_biobank_platedecoder_dmscanlib_ScanLib_CAP_DPI_400 4L
#undef org_biobank_platedecoder_dmscanlib_ScanLib_CAP_DPI_600
#define org_biobank_platedecoder_dmscanlib_ScanLib_CAP_DPI_600 8L
#undef org_biobank_platedecoder_dmscanlib_ScanLib_CAP_IS_SCANNER
#define org_biobank_platedecoder_dmscanlib_ScanLib_CAP_IS_SCANNER 16L
/*
 * Class:     org_biobank_platedecoder_dmscanlib_ScanLib
 * Method:    selectSourceAsDefault
 * Signature: ()Lorg/biobank/platedecoder/dmscanlib/ScanLibResult;
 */
JNIEXPORT jobject JNICALL Java_org_biobank_platedecoder_dmscanlib_ScanLib_selectSourceAsDefault
  (JNIEnv *, jobject);

/*
 * Class:     org_biobank_platedecoder_dmscanlib_ScanLib
 * Method:    getScannerCapability
 * Signature: ()Lorg/biobank/platedecoder/dmscanlib/ScanLibResult;
 */
JNIEXPORT jobject JNICALL Java_org_biobank_platedecoder_dmscanlib_ScanLib_getScannerCapability
  (JNIEnv *, jobject);

/*
 * Class:     org_biobank_platedecoder_dmscanlib_ScanLib
 * Method:    scanImage
 * Signature: (JJIIDDDDLjava/lang/String;)Lorg/biobank/platedecoder/dmscanlib/ScanLibResult;
 */
JNIEXPORT jobject JNICALL Java_org_biobank_platedecoder_dmscanlib_ScanLib_scanImage
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     org_biobank_platedecoder_dmscanlib_ScanLib
 * Method:    scanFlatbed
 * Signature: (JJIILjava/lang/String;)Lorg/biobank/platedecoder/dmscanlib/ScanLibResult;
 */
JNIEXPORT jobject JNICALL Java_org_biobank_platedecoder_dmscanlib_ScanLib_scanFlatbed
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jstring);

/*
 * Class:     org_biobank_platedecoder_dmscanlib_ScanLib
 * Method:    scanAndDecode
 * Signature: (JJIIDDDDLorg/biobank/platedecoder/dmscanlib/DecodeOptions;[Lorg/biobank/platedecoder/dmscanlib/CellRectangle;)Lorg/biobank/platedecoder/dmscanlib/DecodeResult;
 */
JNIEXPORT jobject JNICALL Java_org_biobank_platedecoder_dmscanlib_ScanLib_scanAndDecode
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jdouble, jdouble, jdouble, jdouble, jobject, jobjectArray);

/*
 * Class:     org_biobank_platedecoder_dmscanlib_ScanLib
 * Method:    decodeImage
 * Signature: (JLjava/lang/String;Lorg/biobank/platedecoder/dmscanlib/DecodeOptions;[Lorg/biobank/platedecoder/dmscanlib/CellRectangle;)Lorg/biobank/platedecoder/dmscanlib/DecodeResult;
 */
JNIEXPORT jobject JNICALL Java_org_biobank_platedecoder_dmscanlib_ScanLib_decodeImage
  (JNIEnv *, jobject, jlong, jstring, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
